#
# Stale issues/ PRs
#

# NOTES:
# Repository stale issue/ PR management.
# PRs are marked stale after 14 days, but not closed.

name: Stale
on:
  schedule:
    - cron: '30 1 * * *' # At 1:30 AM, daily

jobs:
  stale:
    runs-on: ubuntu-latest
    name: Flag stale PRs
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: >
            This PR hasn't received any attention lately.
            If it's no longer required it should be **closed**.
            Otherwise please work through review and approval.

          days-before-issue-stale: -1
          days-before-pr-stale: 14

          days-before-issue-close: -1
          days-before-pr-close: -1

          exempt-draft-pr: true

          stale-pr-label: stale
